spring:
    datasource:
        password: yiman
        url: jdbc:postgresql://localhost:5434/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true





